monochrome
torokati44/ruffle-android pull request #178
Opened 2024-06-12 02:46 UTC by soundsnow

![Screenshot_20240612-112539_Trebuchet](https://github.com/brunodev85/winlator/assets/109885044/a8bc7f8e-4988-4bad-98dc-f70df26f2634)

2024-06-12 20:12 UTC, torokati44 commented
Could you please explain briefly what exactly this change achieves?
The screenshot looks irrelevant, I'm not seeing the Ruffle application there.

2024-06-13 08:45 UTC, torokati44 requested changes

2024-06-13 08:45 UTC, torokati44 commented on app/build.gradle.kts
> +        minSdk = 14
```
 /home/runner/work/ruffle-android/ruffle-android/app/src/main/AndroidManifest.xml Error:
	uses-sdk:minSdkVersion 14 cannot be smaller than version 21 declared in library [androidx.appcompat:appcompat-resources:1.7.0] /home/runner/.gradle/caches/transforms-4/6e509871dbb0a44646463976bf102953/transformed/appcompat-resources-1.7.0/AndroidManifest.xml as the library might be using APIs not available in 14
	Suggestion: use a compatible library with a minSdk of at most 14,
		or increase this project's minSdk version to at least 21,
		or use tools:overrideLibrary="androidx.appcompat.resources" to force usage (may lead to runtime failures)
> Task :app:processReleaseMainManifest FAILED
```

2024-06-13 08:47 UTC, torokati44 commented
This initially tiny PR has exploded in scope - and note that there is no point in having dozens of layouts that don't actually do anything.

2024-06-13 10:03 UTC, torokati44 commented
Before you continue further, please define the rough scope and goal of _this specific PR_, and keep the changes in adherence to it. Without this, I'll have to close this PR.

2024-06-13 10:08 UTC, closed without merging

2024-06-13 11:01 UTC, adrian17 commented
Sorry, the part you're missing is that we aren't interested in anything that has to do with Magic DosBox, and especially their (GPL) source.